<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class BagianSeeder extends Seeder
{
	public function run()
	{
		$data = [
			[
				'id_bagian' 	=> '0101',
				'nama_bagian' 	=> 'Sekretaris Jenderal',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 1,
			],
			[
				'id_bagian' 	=> '0201',
				'nama_bagian' 	=> 'Inspektorat',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 2,
			],
			[
				'id_bagian' 	=> '0301',
				'nama_bagian' 	=> 'Deputi Bidang Administrasi',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 3,
			],
			[
				'id_bagian' 	=> '0401',
				'nama_bagian' 	=> 'Deputi Bidang Persidangan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 4,
			],
			[
				'id_bagian' 	=> '0501',
				'nama_bagian' 	=> 'Bagian Organisasi dan Ketatalaksanaan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 5,
			],
			[
				'id_bagian' 	=> '0502',
				'nama_bagian' 	=> 'Bagian Administrasi Keanggotaan dan Kepegawaian',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 5,
			],
			[
				'id_bagian' 	=> '0503',
				'nama_bagian' 	=> 'Bagian Pengembangan Sumber Daya Manusia',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 5,
			],
			[
				'id_bagian' 	=> '0504',
				'nama_bagian' 	=> 'Bagian Hukum',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 5,
			],
			[
				'id_bagian' 	=> '0601',
				'nama_bagian' 	=> 'Bagian Perencanaan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 6,
			],
			[
				'id_bagian' 	=> '0602',
				'nama_bagian' 	=> 'Bagian Administrasi, Gaji, Tunjangan dan Honorarium',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 6,
			],
			[
				'id_bagian' 	=> '0603',
				'nama_bagian' 	=> 'Bagian Pembendaharaan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 6,
			],
			[
				'id_bagian' 	=> '0604',
				'nama_bagian' 	=> 'Bagian Akuntansi dan Pelaporan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 6,
			],
			[
				'id_bagian' 	=> '0701',
				'nama_bagian' 	=> 'Bagian Pengelolaan Sistem Informasi',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 7,
			],
			[
				'id_bagian' 	=> '0702',
				'nama_bagian' 	=> 'Bagian Risalah',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 7,
			],
			[
				'id_bagian' 	=> '0703',
				'nama_bagian' 	=> 'Bagian Kearsipan, Perpustakaan, dan Penerbitan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 7,
			],
			[
				'id_bagian' 	=> '0801',
				'nama_bagian' 	=> 'Bagian Pengelolaan Barang Milik Negara',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 8,
			],
			[
				'id_bagian' 	=> '0802',
				'nama_bagian' 	=> 'Bagian Pemeliharaan dan Perlengkapan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 8,
			],
			[
				'id_bagian' 	=> '0803',
				'nama_bagian' 	=> 'Bagian Layanan Pengadaan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 8,
			],
			[
				'id_bagian' 	=> '0804',
				'nama_bagian' 	=> 'Bagian Pengamanan Dalam',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 8,
			],
			[
				'id_bagian' 	=> '0901',
				'nama_bagian' 	=> 'Bagian Protokol',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 9,
			],
			[
				'id_bagian' 	=> '0902',
				'nama_bagian' 	=> 'Bagian Hubungan Masyarakat dan Fasilitasi Pengaduan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 9,
			],
			[
				'id_bagian' 	=> '0903',
				'nama_bagian' 	=> 'Bagian Pemberitaan dan Media',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 9,
			],
			[
				'id_bagian' 	=> '1001',
				'nama_bagian' 	=> 'Bagian Sekretariat Komite I',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 10,
			],
			[
				'id_bagian' 	=> '1002',
				'nama_bagian' 	=> 'Bagian Sekretariat Komite III',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 10,
			],
			[
				'id_bagian' 	=> '1003',
				'nama_bagian' 	=> 'Bagian Sekretariat Panitia Perancang Undang-Undang',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 10,
			],
			[
				'id_bagian' 	=> '1004',
				'nama_bagian' 	=> 'Bagian Sekretariat BPKK/Kelompok DPD RI di MPR RI',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 10,
			],
			[
				'id_bagian' 	=> '1005',
				'nama_bagian' 	=> 'Bagian Sekretariat Badan Kerja Sama Parlemen',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 10,
			],
			[
				'id_bagian' 	=> '1101',
				'nama_bagian' 	=> 'Bagian Sekretariat Komite II',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1102',
				'nama_bagian' 	=> 'Bagian Sekretariat Komite IV',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1103',
				'nama_bagian' 	=> 'Bagian Sekretariat Persidangan Paripurna Panmus Pangus',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1104',
				'nama_bagian' 	=> 'Bagian Sekretariat Badan Kehormatan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1105',
				'nama_bagian' 	=> 'Bagian Sekretariat Panitia Urusan Rumah Tangga',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1106',
				'nama_bagian' 	=> 'Bagian Sekretariat Badan Akuntabilitas Publik',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 11,
			],
			[
				'id_bagian' 	=> '1201',
				'nama_bagian' 	=> 'Bagian Sekretariat Ketua DPD RI',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 12,
			],
			[
				'id_bagian' 	=> '1202',
				'nama_bagian' 	=> 'Bagian Sekretariat Wakil Ketua DPD RI Bidang I',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 12,
			],
			[
				'id_bagian' 	=> '1203',
				'nama_bagian' 	=> 'Bagian Sekretariat Wakil Ketua DPD RI Bidang II',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 12,
			],
			[
				'id_bagian' 	=> '1204',
				'nama_bagian' 	=> 'Bagian Tata Usaha Pimpinan Sekretariat Jenderal',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 12,
			],
			[
				'id_bagian' 	=> '1301',
				'nama_bagian' 	=> 'Bidang Perancangan dan Pemantauan Peraturan Perundang-Undangan',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 13,
			],
			[
				'id_bagian' 	=> '1302',
				'nama_bagian' 	=> 'Bidang Dokumentasi Jaringan Informasi Hukum Pusat dan Daerah',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 13,
			],
			[
				'id_bagian' 	=> '1401',
				'nama_bagian' 	=> 'Bidang Diseminasi Aspirasi Masyarakat dan Daerah',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 14,
			],
			[
				'id_bagian' 	=> '1402',
				'nama_bagian' 	=> 'Bidang Pengkajian dan Informasi Anggaran Pusat dan Daerah',
				'created_at'    => Time::now(),
				'updated_at'    => Time::now(),
				'id_biro'		=> 14,
			],
		];

		// Using Query Builder
		$this->db->table('tb_bagian')->insertBatch($data);
	}
}
